name: v24.02.1

on:
    push:
        branches:
        - main
    pull_request:
    workflow_dispatch:

jobs:
    call-ci:
        uses: ./.github/workflows/ci.yml
        with:
            cln-version: "v24.02.1"
            pyln-version: "24.02"